apiVersion: apps/v1
kind: Deployment
metadata:
  name: certify-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: certify-client
  template:
    metadata:
      labels:
        app: certify-client
    spec:
      containers:
        - name: certify-client
          image: paulkbln/certify-client
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      restartPolicy: Always


